"use client";

import { motion } from "framer-motion";
import { Download, Copy, Mail, Check } from "lucide-react";
import { useState } from "react";

interface OutputPreviewProps {
  title: string;
  content: string;
  type: "text" | "markdown" | "code" | "table";
  onDownload?: () => void;
  onEmail?: () => void;
}

export default function OutputPreview({ 
  title, 
  content, 
  type,
  onDownload,
  onEmail 
}: OutputPreviewProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-surface border border-border rounded-xl overflow-hidden shadow-notion-sm"
    >
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-border bg-background-secondary">
        <h3 className="text-sm font-medium text-text-primary">{title}</h3>
        
        <div className="flex items-center gap-2">
          <motion.button
            onClick={handleCopy}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="p-2 hover:bg-background-tertiary rounded-lg transition text-text-secondary"
            title="Copy to clipboard"
          >
            {copied ? (
              <Check className="w-4 h-4 text-success" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
          </motion.button>

          {onEmail && (
            <motion.button
              onClick={onEmail}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className="p-2 hover:bg-background-tertiary rounded-lg transition text-text-secondary"
              title="Open in email"
            >
              <Mail className="w-4 h-4" />
            </motion.button>
          )}

          {onDownload && (
            <motion.button
              onClick={onDownload}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className="p-2 hover:bg-background-tertiary rounded-lg transition text-text-secondary"
              title="Download"
            >
              <Download className="w-4 h-4" />
            </motion.button>
          )}
        </div>
      </div>

      {/* Content */}
      <div className="p-6 max-h-96 overflow-y-auto">
        {type === "code" ? (
          <pre className="text-sm text-text-primary font-mono bg-background-tertiary p-4 rounded-lg overflow-x-auto">
            <code>{content}</code>
          </pre>
        ) : type === "table" ? (
          <div className="overflow-x-auto">
            <div 
              className="text-sm text-text-primary"
              dangerouslySetInnerHTML={{ __html: content }}
            />
          </div>
        ) : (
          <div className="prose prose-sm max-w-none">
            <p className="text-sm text-text-primary whitespace-pre-wrap leading-relaxed">
              {content}
            </p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="px-6 py-3 border-t border-border bg-background-secondary">
        <p className="text-xs text-text-tertiary">
          Generated by Proto • Ready to use
        </p>
      </div>
    </motion.div>
  );
}
