'use client'

import { Outfit } from 'next/font/google'
import InfoPageLayout from '@/components/InfoPageLayout'

const outfit = Outfit({ subsets: ['latin'], weight: ['600', '700', '800'] })

export default function TermsOfService() {
  return (
    <InfoPageLayout
      title="Terms of Service"
      subtitle="Please review these terms carefully before using protocolLM. By accessing the platform you acknowledge the limits of AI assistance and agree to operate within Washtenaw County health code requirements."
      eyebrow="Policy update"
    >
      <div className="space-y-6">
        <div className="rounded-xl border border-[#2F5D8A] border-l-4 bg-[#15151a] p-6">
          <div className="mb-3 inline-flex items-center gap-2 rounded-md bg-[#1c1c22] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] ring-1 ring-[#2F5D8A]">
            Please read first
          </div>
          <p>
            protocolLM is a reference tool only. Always verify critical decisions with official health department guidance and licensed professionals. Human
            review is required before acting on any AI output.
          </p>
        </div>

        <section className="rounded-xl border border-[#2a2a32] bg-[#15151a] p-6">
          <h2 className={`text-xl font-bold ${outfit.className}`}>1. Acceptance of Terms</h2>
          <p className="mt-3">
            By accessing or using protocolLM ("the Service"), you agree to be bound by these Terms of Service. These Terms constitute a legally binding
            agreement between you and protocolLM.
          </p>
        </section>

        <section className="rounded-xl border border-[#2F5D8A] border-l-4 bg-[#15151a] p-6">
          <div className="mb-3 inline-flex items-center gap-2 rounded-md bg-[#1c1c22] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] ring-1 ring-[#2F5D8A]">
            2. Critical Disclaimers
          </div>
          <h2 className={`text-xl font-bold ${outfit.className}`}>AI limitations & responsibility</h2>
          <div className="mt-3 inline-flex items-center gap-2 rounded-full bg-[#2F5D8A] px-4 py-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-white">
            Human review required
          </div>
          <ul className="mt-4 space-y-3">
            <li>AI-generated responses may contain inaccuracies, omissions, or misinterpretations of statutes, rules, or local enforcement practices.</li>
            <li>The Service may not reflect real-time changes to county or state policies, inspection procedures, or interpretive guidance.</li>
            <li>Output is probabilistic and may differ when the same question or image is submitted more than once.</li>
            <li>AI models can "hallucinate" or generate plausible-sounding but incorrect information.</li>
            <li>
              Compliance decisions, equipment purchases, staffing changes, and operational adjustments must not be based solely on responses generated by
              the Service. Always verify critical information with official sources.
            </li>
          </ul>
        </section>

        <section className="rounded-xl border border-[#2a2a32] bg-[#15151a] p-6">
          <h2 className={`text-xl font-bold ${outfit.className}`}>3. Indemnification (Hold Harmless)</h2>
          <p className="mt-3">
            You agree to defend, indemnify, and hold harmless protocolLM, its owners, and affiliates from and against any claims, liabilities, damages,
            judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to:
          </p>
          <ul className="mt-3 space-y-2">
            <li>Your use of the Service.</li>
            <li>Any violation of health codes, fines, closures, or legal action taken against your business.</li>
            <li>Your reliance on any information provided by the Service.</li>
            <li>Any claim that your use of AI-generated content violates third-party rights or applicable regulations.</li>
          </ul>
          <p className="mt-3 font-semibold">
            You acknowledge that you maintain sole responsibility for your establishment's compliance with applicable laws and regulations.
          </p>
        </section>

        <section className="rounded-xl border border-[#2a2a32] bg-[#15151a] p-6">
          <h2 className={`text-xl font-bold ${outfit.className}`}>4. Limitation of Liability</h2>
          <p className="mt-3">
            To the fullest extent permitted by law, in no event will protocolLM be liable for any indirect, incidental, special, consequential, or punitive
            damages, including but not limited to loss of profits, revenue, goodwill, or business interruption arising from:
          </p>
          <ul className="mt-3 space-y-2">
            <li>Your use of or inability to use the Service.</li>
            <li>Any AI-generated content, including errors, inaccuracies, or omissions.</li>
            <li>Health code violations, fines, or enforcement actions.</li>
            <li>Any unauthorized access to or alteration of your data.</li>
          </ul>
          <p className="mt-3">
            Our total liability for any claims arising from these Terms or the Service shall not exceed the fees you paid to us in the twelve (12) months
            preceding the event giving rise to the claim.
          </p>
        </section>

        <section className="rounded-xl border border-[#2a2a32] bg-[#15151a] p-6">
          <h2 className={`text-xl font-bold ${outfit.className}`}>5. Subscription & Cancellation</h2>
          <ul className="mt-4 space-y-3">
            <li>
              <strong>Free Trial:</strong> A 7-day trial may be offered. Unless cancelled before the trial ends, your subscription will convert to a paid plan
              at $100/month.
            </li>
            <li>
              <strong>Cancellation:</strong> You may cancel at any time via the self-service billing portal to stop future billing cycles. Access continues
              until the end of your current billing period.
            </li>
            <li>
              <strong>Refunds:</strong> We do not provide refunds for partial months or unused portions of the Service.
            </li>
            <li>
              <strong>Usage Limits:</strong> Your plan includes up to 1,300 checks per month (text questions count as 1 check, photo analysis counts as 2
              checks). Exceeding these limits may result in service interruption until the next billing cycle.
            </li>
          </ul>
        </section>

        <section className="rounded-xl border border-[#2a2a32] bg-[#15151a] p-6">
          <h2 className={`text-xl font-bold ${outfit.className}`}>6. Acceptable Use</h2>
          <p className="mt-3">You agree NOT to:</p>
          <ul className="mt-3 space-y-2">
            <li>Use the Service for any unlawful purpose or in violation of these Terms.</li>
            <li>Attempt to reverse engineer, decompile, or extract the AI models or algorithms.</li>
            <li>Use automated systems (bots, scrapers) to access the Service.</li>
            <li>Share your account credentials with others or create multiple accounts.</li>
            <li>Upload malicious code, viruses, or harmful content.</li>
            <li>Abuse or overload the Service with excessive requests.</li>
          </ul>
        </section>

        <section className="rounded-xl border border-[#2a2a32] bg-[#15151a] p-6">
          <h2 className={`text-xl font-bold ${outfit.className}`}>7. Changes to Terms</h2>
          <p className="mt-3">
            We reserve the right to modify these Terms at any time. We will notify you of material changes via email or through the Service. Your continued
            use after notification constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section className="rounded-xl border border-[#2a2a32] bg-[#15151a] p-6">
          <h2 className={`text-xl font-bold ${outfit.className}`}>8. Contact</h2>
          <p className="mt-3">
            For questions about these Terms, contact:<br />
            <a href="mailto:support@protocollm.org" className="underline underline-offset-2">
              support@protocollm.org
            </a>
          </p>
        </section>
      </div>
    </InfoPageLayout>
  )
}
